import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Typewriter from "typewriter-effect";
import InvoiceTemplate from "../components/InvoiceTemplate/InvoiceTemplate";
import Form from "../components/Form/Form";
import Previewed from "../components/Preview/Preview";
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [service, setService] = useState('invoice');
  const [showPreview, setShowPreview] = useState(false);
  const [formData, setFormData] = useState({});
  const [rows, setRows] = useState(Array(1).fill({id: 0, quantity: 1}));


  const handleChange = (e) => {
    setService(e.target.value);
  }
  
  const handleFormChange = (name, value) => {
    console.log('aaa val in parent');
    setFormData({
      ...formData, [name]: value
    })
  }
  const handleToggle = () => {
    setShowPreview(!showPreview);
  }

   // Table Functions
   const handleTableUpdate = (e, id) => {
    const updateTable = [...rows];
    const currentRowIndex = updateTable.findIndex((row) => row.id === id);
    updateTable[currentRowIndex] = { ...updateTable[currentRowIndex], [e.target.name]: e.target.value }
    setRows(updateTable);
  }
  const handleRowAdd = () => {
    const lastId = rows.length ? rows[rows.length - 1].id : 0;
    setRows((prevRows) => [...prevRows, {id: lastId + 1, quantity: 1}]);
  }

  const handleRowRemove = (id) => {
    setRows((prevRows) => prevRows.filter(item => item.id !== id));
  }

  return (
    <>
      <Head>
        <title>Invoice Receipt Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.header}>
            <h1>Create your  
              <span className={styles.typewriter}>
                <Typewriter
                  options={{
                    strings: [
                      " invoice",
                      " receipt",
                    ],
                    autoStart: true,
                    loop: true,
                    cursor: "",
                    delay: "natural",
                  }}
                />
              </span>
            </h1>
            <div className={styles.services}>
              <h3>Select Service</h3>
              <select name="choice" id="service" defaultValue={service} onChange={handleChange}>
                <option value="receipt">Receipt</option>
                <option value="invoice">Invoice</option>
              </select>
            </div>
          </div>
          <InvoiceTemplate service={service}/>
          {!showPreview && <Form
            prefill={formData}
            rows={rows}
            onFormMod={handleFormChange}
            onPreviewToggle={handleToggle}
            onRowAdd={handleRowAdd}
            onRowRemove={handleRowRemove}
            onTableUpdate={handleTableUpdate}
            />}
          
          {showPreview && <Previewed 
            {...formData}
            rows={rows}
            onPreviewToggle={handleToggle}
          />}
          {/* <form>
            <label htmlFor="opt1">
              <input type="radio" name="tester" id='opt1' />
              Check
            </label>
            <label htmlFor="opt2">
              <input type="radio"  name="tester" id='opt2'/>
              Check222
            </label>
          </form> */}

          {/* <div>
            <h3>Select Template</h3>
            <div>
              <div>
                <h2>Image 1</h2>
              </div>
              <div>
                <h2>Image 2</h2>
              </div>
              <div>
                <h2>Image 3</h2>
              </div>
            </div>
          </div> */}


          {/* ------- */}
          {/* <Image
          className={styles.enlarge}
          src={InvoiceTemp1}
          alt="Next.js Logo"
          priority
        /> */}
        {/* <Image
          className={styles.enlarge}
          src={InvoiceTemp3}
          alt="Next.js Logo"
          priority
        />
        <Image
          className={styles.enlarge}
          src={InvoiceTemp2}
          alt="Next.js Logo"
          priority
        /> */}

        {/* ------- */}

         {/* <form action="">
        <p>A simple mod:</p>
        <div className="cc-selector-2">
            <input id="visa2" type="radio" name="creditcard" value="visa" />
            <label className="drinkcard-cc visa" htmlFor="visa2"></label>
            <input  defaultChecked id="mastercard2" type="radio" name="creditcard" value="mastercard" />
            <label className="drinkcard-cc mastercard"htmlFor="mastercard2"></label>
        </div>
      </form> */}

      {/* ------- */}

      {/* <img class={styles.enlarge} src="https://upload.wikimedia.org/wikipedia/commons/6/6f/OrteliusWorldMap.jpeg" alt="test" />
        <img class={styles.enlarge} src="https://upload.wikimedia.org/wikipedia/commons/6/6f/OrteliusWorldMap.jpeg" alt="test" /> */}
        {/* <img class={styles.enlarge} src="https://upload.wikimedia.org/wikipedia/commons/6/6f/OrteliusWorldMap.jpeg" alt="test" /> */}
        </div>
      </main>
    </>
  )
}
